development:
    certificate: "apns/TdvCertification_dev.pem"

test:
    certificate: "apns/TdvCertification_dev.pem"

staging:
    certificate: "apns/TdvCertification_dev.pem"

production:
    certificate: "apns/TdvCertification_dev.pem"
