development:
    url: "https://gcm-http.googleapis.com/gcm/send?="
    token: "/topics/global"
    authorization: 'key=AIzaSyC20LFgVKFp-shpY-fYV3jrUOqVSIztcVc'
test:
    # TODO: check topen path
    url: "https://gcm-http.googleapis.com/gcm/send?="
    token: "/test/"
    authorization: 'key=AIzaSyC20LFgVKFp-shpY-fYV3jrUOqVSIztcVc'

staging:
    url: "https://gcm-http.googleapis.com/gcm/send?="
    token: "/topics/global"
    authorization: ''

production:
    url: "https://gcm-http.googleapis.com/gcm/send?="
    token: "/topics/global"
    authorization: ''
