test: &default
  client_id: clientid
  client_secret: clientsecret
  mode: sandbox

development:
  <<: *default

staging:
  <<: *default

production:
  client_id: clientid
  client_secret: clientsecret
  mode: live
