development:
  secret_key_base: f790a333b0b240394d8a098c109475c8a0945619091874eec2f397bc1f8b4098c8992f89d1f83cc84bc4a1ac160167680106a101f4bf0a227b5f3b3f611de2ef

test:
  secret_key_base: d1d4e97d95a3c912942e964d069057523c632aae0b7dc7d6f805673a7e18c4e73b0ff89785df185faacc50c07a3512d2da488de73be0b028bd951e85fea481e5

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
